# Frigate configuration file
telemetry:
  version_check: False
auth:
  enabled: False
tls:
  enabled: False
proxy:
  header_map:
    user: X-Auth-Request-Preferred-Username
    role: X-Auth-Request-Groups
detectors:
  onnx_0:
    type: onnx
  onnx_1:
    type: onnx
model:
  model_type: yolo-generic
  width: 320 # <--- should match the imgsize set during model export
  height: 320 # <--- should match the imgsize set during model export
  input_tensor: nchw
  input_dtype: float
  path: /config/model_cache/yolov9-s-320.onnx
  labelmap_path: /labelmap/coco-80.txt
semantic_search:
  enabled: false
  model_size: large
face_recognition:
  enabled: false
  model_size: large
lpr:
  enabled: true
  device: GPU
  model_size: large
classification:
  bird:
    enabled: false
mqtt:
  enabled: false
audio:
  enabled: false
birdseye:
  enabled: false
go2rtc:
  streams:
    office:
      - rtspx://192.168.5.1:7441/qX68ANZhKnf4rA3T
detect:
  enabled: true
objects:
  track:
    - person
    - car
motion:
  enabled: true
record:
  enabled: true
  retain:
    mode: motion
    days: 3
snapshots:
  enabled: true
  retain:
    mode: motion
    default: 30
ffmpeg:
  hwaccel_args: preset-nvidia
  output_args:
    record: preset-record-generic
cameras:
  # Define at least one camera
  office:
    ffmpeg:
      inputs:
        - path: rtsps://192.168.5.1:7441/qX68ANZhKnf4rA3T
          roles:
            - record
        - path: rtsps://192.168.5.1:7441/16Y62oLc2uVzzotI # low-res stream for object detection
          roles:
            - detect
    motion:
      mask:
        - 0.293,0.041,0,0.038,0,0,0.295,0
        - 0.219,0.249,0.223,0.131,0.29,0.134,0.282,0.246
        - 0.293,0.07,0.299,0.006,0.465,0.013,0.461,0.087
        - 0.69,1,0.829,0.591,0.863,0.242,0.867,0,1,0,1,1
    zones: {}
