image:
  repository: ghcr.io/blakeblackshear/frigate
  tag: 0.16.3-tensorrt@sha256:7940134770b1f050e7b4ad6cf716fda011e15fe53ea6cc7e5066b8f1df6335bd
  pullPolicy: IfNotPresent

extraVolumes:
  - name: trusted-headers
    configMap:
      name: trusted-headers
gpu:
  nvidia:
    enabled: true
    runtimeClassName: nvidia
# -- declare additional volume mounts
extraVolumeMounts:
  - name: trusted-headers
    mountPath: /usr/local/nginx/conf/proxy_trusted_headers.conf
    subPath: proxy_trusted_headers.conf
persistence:
  config:
    enabled: true
    storageClass: openebs-zfspv
    size: 20Gi
    skipuninstall: true
  media:
    enabled: true
    storageClass: openebs-zfspv
    size: 1Ti
    skipuninstall: true
resources:
  limits:
    memory: "16Gi"
  requests:
    cpu: "1"
    memory: "1Gi"

securityContext:
  privileged: true

env:
  TZ: "America/Los_Angeles"
  #HSA_OVERRIDE_GFX_VERSION: "11.0.0"
config: "REPLACE_ME"
