image:
  repository:  ghcr.io/external-secrets/external-secrets
  pullPolicy: IfNotPresent
  # -- The image tag to use. The default is the chart appVersion.
  tag: "v1.2.0@sha256:9d9ef89a7e3832345039fbf49782f89e86f36f90b2aefaad1d7e84b364f1a019"
  # -- The flavour of tag you want to use
  # There are different image flavours available, like distroless and ubi.
  # Please see GitHub release notes for image tags for these flavors.
  # By default, the distroless image is used.
  flavour: ""
