apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


helmCharts:
  - name: zfs-localpv
    namespace: kube-system
    includeCRDs: true
    releaseName: openebs-zfs
    repo: https://openebs.github.io/zfs-localpv
    valuesFile: values.yaml
    version: 2.9.0

resources:
  - storage-class.yaml
  - snapshot.yaml
