apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - "pvc.yaml"
  - "netpol.yaml"

helmCharts:
  - name: app-template
    repo: https://bjw-s-labs.github.io/helm-charts
    releaseName: zwave
    version: 4.5.0
    valuesFile: values.yaml
