bypassDnsResolution: 'true'
replicas: 1
image:
  repository: ghcr.io/postfinance/kubelet-csr-approver
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.2.12@sha256:08d00647e168187c1a57296b50cd79db7af59e3ecdfd12eb9fc221762b721e99"
