apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: error-oauth-middleware
  namespace: default
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth-proxy
      port: 80
    query: "/oauth2/sign_in?rd={url}"
