apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default
resources:
  - fa-middleware.yaml
  - error-middleware.yaml
  - tls-option.yaml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    releaseName: traefik
    version: 37.4.0
    valuesFile: values.yaml
    includeCRDs: true
    namespace: default
