name: Mirror to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # Every day at 04:00 UTC

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: ${{ github.server_url != 'https://github.com' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitHub.com
        env:
          GH_TOKEN: ${{ secrets.MIRROR_GITHUB_TOKEN }}
        run: |
          git remote add github https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git push github main
