name: Renovate

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 */3 * * *'

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    if: ${{ github.server_url != 'https://github.com' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Run Renovate
        uses: https://github.com/renovatebot/github-action@a7e89c349a53ab0c9d8458eb85f4b415e55848e7 # v44.2.3
        env:
            LOG_LEVEL: debug
            GITHUB_COM_TOKEN: ${{ secrets.GH_COM_TOKEN }}
            RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          token: ${{ secrets.PAT }}
          renovate-version: "42.66.9"
